# Generated by Django 3.0.5 on 2020-04-15 03:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('ID', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nickName', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Turnip_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('isSell', models.BooleanField(default=True)),
                ('report_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date reported')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnips.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Island',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islandName', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('sphere', models.CharField(choices=[('North', 'North sphere'), ('South', 'South sphere')], default='North', max_length=5)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnips.Client')),
            ],
        ),
    ]
